# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CharityApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Work this time damn you
  # Pods for CharityApp
pod 'SwiftSoup'
end
